#!/usr/bin/env ruby
# frozen_string_literal: true

# This is the executable for the decidim-module-factory gem.
# It extends the original decidim generator with a new command.

# Find original decidim executable from decidim-generators gem
begin
  gem "decidim-generators"
rescue Gem::LoadError
  puts "Could not load decidim-generators. Make sure it is installed."
  exit 1
end

if ARGV[0] == "--module-factory"
  ARGV.shift
  ARGV.unshift("component")
end

# Fallback to original decidim command
decidim_executable = Gem.bin_path("decidim-generators", "decidim")
load decidim_executable
