#!/usr/bin/env ruby
# frozen_string_literal: true

# This is the executable for the decidim-module-factory gem.
# It extends the original decidim generator with a new command.

# We need to manually require the dev environment to load all of Decidim
# and its dependencies correctly.
require "decidim/dev"
require "decidim/module_factory/generator"

if ARGV[0] == "--module-factory"
  # Remove the --module-factory flag
  ARGV.shift
  # Prepend the command that the generator expects
  ARGV.unshift("component")

  # Start our generator
  Decidim::ModuleFactory::Generator.start
else
  puts "Invalid command. Usage: decidim-module-factory --module-factory NAME [options]"
  exit 1
end
