version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: social-resonance/Dockerfile
    volumes:
      - ..:/decidim
      - bundle:/usr/local/bundle
      - node_modules:/decidim/social-resonance/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    ports:
      - '3000:3000'
    links:
      - pg
      - redis
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  worker:
    build:
      context: ..
      dockerfile: social-resonance/Dockerfile
    volumes:
      - ..:/decidim
      - bundle:/usr/local/bundle
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    links:
      - pg
      - redis
    command: bundle exec sidekiq
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  redis-data: {}