# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

gem "decidim", path: ".."
gem "decidim-ai", path: ".."
gem "decidim-collaborative_texts", path: ".."
gem "decidim-conferences", path: ".."
gem "decidim-design", path: ".."
gem "decidim-elections", path: ".."
gem "decidim-initiatives", path: ".."
gem "decidim-templates", path: ".."
gem "decidim-calendar", git: "https://github.com/decidim-ice/decidim-module-calendar"
gem "decidim-decidim_awesome", git: "https://github.com/decidim-ice/decidim-module-decidim_awesome", branch: "release/0.30-stable"


gem "bootsnap", "~> 1.4"

gem "puma", ">= 6.3.1"

group :development, :test do
  gem "byebug", "~> 11.0", platform: :mri

  gem "decidim-dev", path: ".."

  gem "brakeman", "~> 7.0"
  gem "parallel_tests", "~> 4.2"
end

group :development do
  gem "letter_opener_web", "~> 2.0"
  gem "listen", "~> 3.1"
  gem "web-console", "~> 4.2"
end
gem "sidekiq"

group :production do
end

group :development do
  # Profiling gems
  gem "bullet"
  gem "flamegraph"
  gem "memory_profiler"
  gem "rack-mini-profiler", require: false
  gem "stackprof"
end
